# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        api_key_user_provider:
            id: App\Security\ApiKeyUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            anonymous: ~
            pattern: ^/api/v2
            stateless: true
            simple_preauth:
                authenticator: App\Security\ApiKeyAuthenticator
            provider: api_key_user_provider
        main:
            provider: fos_userbundle
            anonymous: ~
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /dashboard
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path: /login
                use_forward: false
                failure_path: /login
                provider: fos_userbundle

                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service
            remember_me:
                secret: '%secret%'
            logout:
                target: /login
                handlers: [ 'App\EventListener\LogoutRequestLoggerListener' ]
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                default_target_path: /dashboard
                always_use_default_target_path: false

    role_hierarchy:
        ROLE_ADMIN_USER_ADMIN:
            - ROLE_ADMIN_USER_LIST
            - ROLE_ADMIN_USER_VIEW
        ROLE_ADMIN_USER_SUPPORT:
            - ROLE_ADMIN_USER_LIST
            - ROLE_ADMIN_USER_VIEW
            - ROLE_ADMIN_USER_EDIT
        ROLE_ADMIN_USER_SUPER:
            - ROLE_ADMIN_USER_ALL
            - ROLE_ADMIN_USER_EDITROLES
        ROLE_ADMIN_PROFILE_ADMIN:
            - ROLE_ADMIN_PROFILE_LIST
            - ROLE_ADMIN_PROFILE_VIEW
        ROLE_ADMIN_PROFILE_SUPER:
            - ROLE_ADMIN_PROFILE_ALL
        ROLE_ADMIN_NEWS_ADMIN:
            - ROLE_SONATA_NEWS_ADMIN_POST_ALL
            - ROLE_SONATA_NEWS_ADMIN_COMMENT_ALL
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL
            - ROLE_SONATA_CLASSIFICATION_ADMIN_TAG_ALL
            - ROLE_SONATA_CLASSIFICATION_ADMIN_COLLECTION_ALL
            - ROLE_SONATA_CLASSIFICATION_ADMIN_CONTEXT_ALL

        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN_USER_ADMIN, ROLE_ADMIN_PROFILE_ADMIN]
        ROLE_SUPPORTER: [ROLE_ADMIN, ROLE_ADMIN_USER_SUPPORT]
        ROLE_COPYWRITER: [ROLE_ADMIN, ROLE_ADMIN_NEWS_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ADMIN_USER_SUPER, ROLE_ADMIN_PROFILE_SUPER]
        ROLE_API: [ROLE_USER]

    access_decision_manager:
        strategy: unanimous

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-google, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/buy, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/wallet, roles: ROLE_USER }
        - { path: ^/downloadwpplugin, roles: ROLE_USER }
        - { path: ^/ico_referral, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/token, roles: ROLE_USER }
        - { path: ^/api/v2, roles: ROLE_API }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
