monolog:
    channels: ['user_action', 'admin_action']
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event','!user_action', '!admin_action']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        user_action:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/actions.log'
            channels: ['user_action']
            formatter: monolog.formatter.user_action
        admin_action:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/admin_action.log'
            channels: ['admin_action']
            formatter: monolog.formatter.admin_action
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
