App\Entity\Classification\Collection:
    type: entity
    repositoryClass: Doctrine\ORM\EntityRepository
    table: classification__collection

    id:
        id:
           type: integer
           generator:
                strategy: AUTO
